In [10]:
import tensorflow as tf
# Three Data Type
# Constant, Variable, Placeholder
# Initialization of the tensor
x = tf.constant(4, shape =(1,1), dtype = tf.float64)
a = tf.constant([[1,2,3], [2,4,5]])
print(x)

c = tf.zeros((3,3))
print(c)
d = tf.ones((2,3))
e = tf.eye(3) # Identical matrix 

# random 
f = tf.random.normal((3,3), mean =0, stddev= 1)
print(f)
g = tf.random.uniform((1, 3), minval = 0, maxval =1)
h = tf.range(start=1, limit=10, delta= 2)
print(h)
i = tf.cast(x, dtype=tf.float64)
print(f)

tf.__version__


tf.Tensor([[4.]], shape=(1, 1), dtype=float64)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.55593085  0.41154915  1.1344503 ]
 [-1.250229    1.3402162   0.30849996]
 [-1.1662678   1.0166917  -0.12748164]], shape=(3, 3), dtype=float32)
tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)
tf.Tensor(
[[ 0.55593085  0.41154915  1.1344503 ]
 [-1.250229    1.3402162   0.30849996]
 [-1.1662678   1.0166917  -0.12748164]], shape=(3, 3), dtype=float32)


'2.4.1'